audio_data:
  type: "log"
  sampling_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  window: 'hamming'

model:
  enc: 
    n_head: 8           
    d_model: 40        
    d_k: 5             
    d_v: 5             
    d_hidden: 128       
    dropout: 0.2
  dec: 
    embed_dim: 64
    d_hidden: 128
    num_layers: 1
    embed_dropout: 0.1
    var_dropout: 0.2
  vocab_size: 4866  # 4866 for vivos 7018 for vlsp
  feature_dim: 40   # sync with dataset.py
  name : 'SAA'
  share_weight: False
  pad_id: 0
  sos_id: 1
  eos_id: 2
  blank_id: 4
  
# Vivos
training:
  epochs: 100
  batch_size: 8
  accumulation_steps: 4
  save_path: "C:/paper/self-acoustic/save_folder"
  train_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/train_w2i.json"
  dev_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/test_w2i.json"
  test_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/test_w2i.json"
  vocab_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/vocab_w2i.json"
  cmvn_stats : "workspace/rna/conv-rnnt/data/cmvn_stats.pt"
  log_path: "C:/paper/self-acoustic/logs"
  reload: False

# VLSP
# training:
#   epochs: 100
#   batch_size: 2
#   accumulation_steps: 4
#   save_path: "C:/paper/self-acoustic/save_folder"
#   train_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/train_w2i.json"
#   dev_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/val_w2i.json"
#   test_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/test_w2i.json"
#   vocab_path : "C:/paper/raw_data/Vietnamese-Speech-to-Text-datasets/VLSP/vocab_w2i.json"
#   cmvn_stats : "workspace/rna/conv-rnnt/data/cmvn_stats.pt"
#   log_path: "C:/paper/self-acoustic/logs"
#   reload: False

optim:
  # type: sgd
  # lr: 0.0005
  # momentum: 0.9
  # weight_decay: 0
  # begin_to_adjust_lr: 60
  # nesterov: None
  # decay_rate: 0.5

  type: adam
  lr: 0.001
  weight_decay: 0
  decay_rate: 0.5

scheduler:
  lr_initial: 0.001
  n_warmup_steps: 1000

rnnt_loss:
  blank: 4
  reduction: "mean" 