model:
  enc: 
    n_head: 8
    d_model: 512               
    d_hidden: 1024       
    dropout: 0.2
    n_layer: 3
  dec: 
    embed_dim: 512
    d_hidden: 512
    num_layers: 2
    embed_dropout: 0.2
    var_dropout: 0.1
  vocab_size: 4866
  feature_dim: 160   # sync with dataset.py
  name : 'SAA'
  share_weight: False
  pad_id: 0
  sos_id: 1
  eos_id: 2
  blank_id: 0
  spec_augment: False
  mF: 2
  F: 15
  mT: 2
  pS: 0.05
  

training:
  epochs: 100
  batch_size: 8
  accumulation_steps: 1
  save_path: "workspace/Self-Attention-Acoustic/saves2"
  train_path : "workspace/dataset/train_w2i.json"
  dev_path : "workspace/dataset/test_w2i.json"
  test_path : "workspace/dataset/test_w2i.json"
  vocab_path : "workspace/dataset/vocab_w2i.json"
  cmvn_stats : "workspace/dataset/cmvn_stats.pt"
  log_path: "workspace/Self-Attention-Acoustic/logs"
  infer_path: "workspace/Self-Attention-Acoustic/logs/results.txt"
  reload: False

optim:
  # type: sgd
  # lr: 0.0005
  # momentum: 0.9
  # weight_decay: 0
  # begin_to_adjust_lr: 60
  # nesterov: None
  # decay_rate: 0.5

  type: adam
  lr: 0.0003
  weight_decay: 0.0
  decay_rate: 0.5

scheduler:
  lr_initial: 0.0003
  n_warmup_steps: 15000

loss:
  # type: cross_entropy 
  # blank: 4
  # reduction: mean
  # label_smoothing: 0.1

  type: kldiv 
  reduction: batchmean
  
  ctc_weight: 0.4
  ctc_reduction: mean

  
